/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LangRouteImport } from './routes/$lang'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LangIndexRouteImport } from './routes/$lang/index'
import { Route as LangDoneerRouteImport } from './routes/$lang/doneer'
import { Route as LangSeminaristenIndexRouteImport } from './routes/$lang/seminaristen.index'
import { Route as LangSeminaristenSlugRouteImport } from './routes/$lang/seminaristen.$slug'

const LangRoute = LangRouteImport.update({
  id: '/$lang',
  path: '/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LangIndexRoute = LangIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangRoute,
} as any)
const LangDoneerRoute = LangDoneerRouteImport.update({
  id: '/doneer',
  path: '/doneer',
  getParentRoute: () => LangRoute,
} as any)
const LangSeminaristenIndexRoute = LangSeminaristenIndexRouteImport.update({
  id: '/seminaristen/',
  path: '/seminaristen/',
  getParentRoute: () => LangRoute,
} as any)
const LangSeminaristenSlugRoute = LangSeminaristenSlugRouteImport.update({
  id: '/seminaristen/$slug',
  path: '/seminaristen/$slug',
  getParentRoute: () => LangRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/$lang/doneer': typeof LangDoneerRoute
  '/$lang/': typeof LangIndexRoute
  '/$lang/seminaristen/$slug': typeof LangSeminaristenSlugRoute
  '/$lang/seminaristen/': typeof LangSeminaristenIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$lang/doneer': typeof LangDoneerRoute
  '/$lang': typeof LangIndexRoute
  '/$lang/seminaristen/$slug': typeof LangSeminaristenSlugRoute
  '/$lang/seminaristen': typeof LangSeminaristenIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/$lang/doneer': typeof LangDoneerRoute
  '/$lang/': typeof LangIndexRoute
  '/$lang/seminaristen/$slug': typeof LangSeminaristenSlugRoute
  '/$lang/seminaristen/': typeof LangSeminaristenIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$lang'
    | '/$lang/doneer'
    | '/$lang/'
    | '/$lang/seminaristen/$slug'
    | '/$lang/seminaristen/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$lang/doneer'
    | '/$lang'
    | '/$lang/seminaristen/$slug'
    | '/$lang/seminaristen'
  id:
    | '__root__'
    | '/'
    | '/$lang'
    | '/$lang/doneer'
    | '/$lang/'
    | '/$lang/seminaristen/$slug'
    | '/$lang/seminaristen/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LangRoute: typeof LangRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$lang': {
      id: '/$lang'
      path: '/$lang'
      fullPath: '/$lang'
      preLoaderRoute: typeof LangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/': {
      id: '/$lang/'
      path: '/'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/doneer': {
      id: '/$lang/doneer'
      path: '/doneer'
      fullPath: '/$lang/doneer'
      preLoaderRoute: typeof LangDoneerRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/seminaristen/': {
      id: '/$lang/seminaristen/'
      path: '/seminaristen'
      fullPath: '/$lang/seminaristen/'
      preLoaderRoute: typeof LangSeminaristenIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/seminaristen/$slug': {
      id: '/$lang/seminaristen/$slug'
      path: '/seminaristen/$slug'
      fullPath: '/$lang/seminaristen/$slug'
      preLoaderRoute: typeof LangSeminaristenSlugRouteImport
      parentRoute: typeof LangRoute
    }
  }
}

interface LangRouteChildren {
  LangDoneerRoute: typeof LangDoneerRoute
  LangIndexRoute: typeof LangIndexRoute
  LangSeminaristenSlugRoute: typeof LangSeminaristenSlugRoute
  LangSeminaristenIndexRoute: typeof LangSeminaristenIndexRoute
}

const LangRouteChildren: LangRouteChildren = {
  LangDoneerRoute: LangDoneerRoute,
  LangIndexRoute: LangIndexRoute,
  LangSeminaristenSlugRoute: LangSeminaristenSlugRoute,
  LangSeminaristenIndexRoute: LangSeminaristenIndexRoute,
}

const LangRouteWithChildren = LangRoute._addFileChildren(LangRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LangRoute: LangRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
